services:
  redis:
    image: redis:7-alpine
    container_name: apcs-redis
    ports:
      - "6379:6379"
    volumes:
      - apcs_redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

  mailpit:
    image: axllent/mailpit:latest
    container_name: apcs-mailpit
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  apcs_redis_data:
