<Project Sdk="MSTest.Sdk">
  <PropertyGroup>
    <AssemblyName>APCS.Domain.UnitTests</AssemblyName>
    <RootNamespace>APCS.Domain.UnitTests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Domain\Domain.csproj" />
  </ItemGroup>
</Project>
