<Project Sdk="MSTest.Sdk">
  <PropertyGroup>
    <AssemblyName>APCS.Application.UnitTests</AssemblyName>
    <RootNamespace>APCS.Application.UnitTests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
    <PackageReference Include="Moq" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Application\Application.csproj" />
  </ItemGroup>
</Project>
