<Project Sdk="MSTest.Sdk">
  <PropertyGroup>
    <AssemblyName>APCS.Common.UnitTests</AssemblyName>
    <RootNamespace>APCS.Common.UnitTests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.Extensions.Configuration" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Common\Common.csproj" />
  </ItemGroup>
</Project>
