<Project Sdk="MSTest.Sdk">
  <PropertyGroup>
    <AssemblyName>APCS.Api.UnitTests</AssemblyName>
    <RootNamespace>APCS.Api.UnitTests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Moq" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\API\API.csproj" />
  </ItemGroup>
</Project>
